server:
  port: 8081
spring:
  datasource:
    url: ${JPA_POSTGRES_CONNECTION_STRING}
    username: ${JPA_POSTGRES_USER}
    password: ${JPA_POSTGRES_PWD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
