server:
  port: 8081
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    datasource:
      platform: postgres
      url: $JPA_POSTGRES_CONNECTION_STRING
      username: postgres
      password: $JPA_POSTGRES_PWD